### ISSUE TITLE
Implement `semantic-release` for automatic release workflow

### ISSUE THREAD

**Issue by dslovinsky** [quarks-css/quarks#4]
Quarks are not ready to be published yet but once 1.0 is complete we should integrate [semantic-release](https://github.com/semantic-release/semantic-release/tree/master).

**Comment by jpwallace22** [comment]
@dslovinsky Can you add us as `members` for `quarks`? I need to set up a fine-grained personal access token for `semantic-release` but I'm not part of quarks. 

![Screen Shot 2023-05-13 at 7 24 53 PM](https://github.com/quarks-css/quarks/assets/93415734/2fad76af-ec5e-4893-b2fe-88a12a9c9c19)
